database:
  sqlserver:
    password: "![CHANGE_ME_ENCRYPT_WITH_SECURE_PROPERTIES_TOOL]"

email:
  smtp:
    password: "![CHANGE_ME_ENCRYPT_WITH_SECURE_PROPERTIES_TOOL]"

sftp:
  password: "![CHANGE_ME_ENCRYPT_WITH_SECURE_PROPERTIES_TOOL]"
